name: Deploy to server

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Dev
        uses: appleboy/ssh-action@master
        with:
          host: 103.171.45.77
          username: cltadmin
          password: "Singh@1989raj"
          script: |
            powershell.exe -Command "cd C:\inetpub\application1\app\; git fetch; git checkout dev; git pull origin dev"

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to ProdServer
        uses: appleboy/ssh-action@master
        with:
          host: 103.171.45.79
          username: cltadmin
          password: "Singh@1989raj"
          script: |
            powershell.exe -Command "cd C:\inetpub\application1\app\; git fetch; git checkout master; git pull origin master"
